### ISSUE TITLE
file(missing) import error

### ISSUE THREAD

**Issue by willmckinley** [arnauddegiuli/HomeSnap#5]
Missing file/import error.
import com.homesnap.engine.controller.what.StateName;

**Comment by arnauddegiuli** [comment]
sorry I m doing a "too" big refactor to simplify the engine.... so actually it is a bit a mess...
Try with this more stable branch: https://github.com/arnauddegiuli/HomeSnap/tree/engineOptimization
it should work better.

**Comment by Danielocean** [comment]
Thanks.I'll check out and report back.

**Comment by Danielocean** [comment]
The project is working now.Thanks for pointing out new repo.However  'Log' thing was not working and import error was not resolving.(I'm guessing having to take something due to visibility or scope issue). But I swapped with my custom log and everything went fine.

**Comment by arnauddegiuli** [comment]
The master branch has been repaired.
I close the issue.
